### ISSUE TITLE
Results panel is displayed, but no controls are shown

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/diffusion#4] opened 2016-12-20 22:35 UTC
I opened the galFiltered network and selected CLB2, GDS1, and PFK27 (YPR119W, YOL136C, YOR355W). Next, I right clicked on a selected node and chose Apps | Diffuse. The diffusion apparently occurred (... the diffusion columns were added to the node table), but no controls appeared in the Results Panel.

After some experimenting, I was able to get the Diffusion Output controls to appear by clicking on the Diffusion Results tab.

Certainly, the controls need to appear under all circumstances.

**Comment by keiono** [comment] 2016-12-22 00:27
Could not reproduce this in the latest version.

**Comment by bdemchak** [comment] 2016-12-22 01:45
Would you try all tests on windows??

Barry Demchak -- from my mobile phone

**Comment by ericsage** [comment] 2016-12-30 20:47
I could not reproduce this issue in Windows

**Comment by bdemchak** [comment] 2017-01-31 17:13
It's back ... here's what I see ...

![image](https://cloud.githubusercontent.com/assets/3696094/22475893/5f76615e-e795-11e6-9f78-7c462a3c4346.png)

When I click on the Diffusion Output tab, I get a proper display. It seems like there must be an event race somewhere:

![image](https://cloud.githubusercontent.com/assets/3696094/22475911/75501024-e795-11e6-8c8e-f163f4b962dc.png)

**Comment by keiono** [comment] 2017-04-14 21:46
Cannot be fixed with my skill.  This requires low level Windows/Java 2D rendering bridge code debugging skill.  Also, could not reproduce this in Windows 10 with Java 8 u121 (on VMWare fusion).

**Closed as completed** 2017-04-17 21:48 UTC
Labels: user interface
